export const countryData = {
  AD: {
    name: 'Andorra',
    iso: 'AD',
    id: '020',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  AE: {
    name: 'United Arab Emirates',
    iso: 'AE',
    id: '784',
    attributes: {
      drivingSide: 'right',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-yellow',
      hemisphere: 'northern',
    },
  },
  AF: {
    name: 'Afghanistan',
    iso: 'AF',
    id: '004',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  AG: {
    name: 'Antigua and Barbuda',
    iso: 'AG',
    id: '028',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  AI: {
    name: 'Anguilla',
    iso: 'AI',
    id: '660',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  AL: {
    name: 'Albania',
    iso: 'AL',
    id: '008',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: ['white-white', 'yellow-white'],
      hemisphere: 'northern',
    },
  },
  AM: {
    name: 'Armenia',
    iso: 'AM',
    id: '',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  AO: {
    name: 'Angola',
    iso: 'AO',
    id: '051',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  AQ: {
    name: 'Antarctica',
    iso: 'AQ',
    id: '010',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  AR: {
    name: 'Argentina',
    iso: 'AR',
    id: '032',
    attributes: {
      drivingSide: 'right',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: ['white-white', 'white-yellow', 'yellow_white-white'],
      hemisphere: 'southern',
    },
  },
  AS: {
    name: 'American Samoa',
    iso: 'AS',
    id: '016',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: 'southern',
    },
  },
  AT: {
    name: 'Austria',
    iso: 'AT',
    id: '040',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  AU: {
    name: 'Australia',
    iso: 'AU',
    id: '036',
    attributes: {
      drivingSide: 'left',
      cameraGen: [1, 2, 3, 4],
      officialCoverage: 'yes',
      roadLines: ['white-white', 'yellow-yellow'],
      hemisphere: 'southern',
    },
  },
  AW: {
    name: 'Aruba',
    iso: 'AW',
    id: '533',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  AX: {
    name: 'Åland Islands',
    iso: 'AX',
    id: '248',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  AZ: {
    name: 'Azerbaijan',
    iso: 'AZ',
    id: '031',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  BA: {
    name: 'Bosnia and Herzegovina',
    iso: 'BA',
    id: '070',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  BB: {
    name: 'Barbados',
    iso: 'BB',
    id: '052',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  BD: {
    name: 'Bangladesh',
    iso: 'BD',
    id: '050',
    attributes: {
      drivingSide: 'left',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  BE: {
    name: 'Belgium',
    iso: 'BE',
    id: '056',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  BF: {
    name: 'Burkina Faso',
    iso: 'BF',
    id: '854',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  BG: {
    name: 'Bulgaria',
    iso: 'BG',
    id: '100',
    attributes: {
      drivingSide: 'right',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  BH: {
    name: 'Bahrain',
    iso: 'BH',
    id: '048',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  BI: {
    name: 'Burundi',
    iso: 'BI',
    id: '108',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  BJ: {
    name: 'Benin',
    iso: 'BJ',
    id: '204',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  BL: {
    name: 'Saint Barthelemy',
    iso: 'BL',
    id: '652',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  BM: {
    name: 'Bermuda',
    iso: 'BM',
    id: '060',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  BN: {
    name: 'Brunei',
    iso: 'BN',
    id: '096',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  BO: {
    name: 'Bolivia',
    iso: 'BO',
    id: '068',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: ['white-white', 'yellow-white'],
      hemisphere: 'southern',
    },
  },
  BQ: {
    name: 'Bonaire, Saint Eustatius and Saba ',
    iso: 'BQ',
    id: '535',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  BR: {
    name: 'Brazil',
    iso: 'BR',
    id: '076',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: ['northern', 'southern'],
    },
  },
  BS: {
    name: 'Bahamas',
    iso: 'BS',
    id: '044',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  BT: {
    name: 'Bhutan',
    iso: 'BT',
    id: '064',
    attributes: {
      drivingSide: 'left',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  BV: {
    name: 'Bouvet Island',
    iso: 'BV',
    id: '074',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  BW: {
    name: 'Botswana',
    iso: 'BW',
    id: '072',
    attributes: {
      drivingSide: 'left',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-yellow',
      hemisphere: 'southern',
    },
  },
  BY: {
    name: 'Belarus',
    iso: 'BY',
    id: '112',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  BZ: {
    name: 'Belize',
    iso: 'BZ',
    id: '084',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  CA: {
    name: 'Canada',
    iso: 'CA',
    id: '124',
    attributes: {
      drivingSide: 'right',
      cameraGen: [1, 2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: 'northern',
    },
  },
  CC: {
    name: 'Cocos Islands',
    iso: 'CC',
    id: '166',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  CD: {
    name: 'Democratic Republic of the Congo',
    iso: 'CD',
    id: '180',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: ['northern', 'southern'],
    },
  },
  CF: {
    name: 'Central African Republic',
    iso: 'CF',
    id: '140',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  CG: {
    name: 'Republic of the Congo',
    iso: 'CG',
    id: '178',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: ['northern', 'southern'],
    },
  },
  CH: {
    name: 'Switzerland',
    iso: 'CH',
    id: '756',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  CI: {
    name: 'Ivory Coast',
    iso: 'CI',
    id: '384',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  CK: {
    name: 'Cook Islands',
    iso: 'CK',
    id: '184',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  CL: {
    name: 'Chile',
    iso: 'CL',
    id: '152',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: ['white-white', 'yellow-white'],
      hemisphere: 'southern',
    },
  },
  CM: {
    name: 'Cameroon',
    iso: 'CM',
    id: '120',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  CN: {
    name: 'China',
    iso: 'CN',
    id: '156',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  CO: {
    name: 'Colombia',
    iso: 'CO',
    id: '170',
    attributes: {
      drivingSide: 'right',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: ['northern', 'southern'],
    },
  },
  CR: {
    name: 'Costa Rica',
    iso: 'CR',
    id: '188',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  CU: {
    name: 'Cuba',
    iso: 'CU',
    id: '192',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  CV: {
    name: 'Cabo Verde',
    iso: 'CV',
    id: '132',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  CW: {
    name: 'Curaçao',
    iso: 'CW',
    id: '531',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  CX: {
    name: 'Christmas Island',
    iso: 'CX',
    id: '162',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  CY: {
    name: 'Cyprus',
    iso: 'CY',
    id: '196',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  CZ: {
    name: 'Czechia',
    iso: 'CZ',
    id: '203',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  DE: {
    name: 'Germany',
    iso: 'DE',
    id: '276',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  DJ: {
    name: 'Djibouti',
    iso: 'DJ',
    id: '262',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  DK: {
    name: 'Denmark',
    iso: 'DK',
    id: '208',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  DM: {
    name: 'Dominica',
    iso: 'DM',
    id: '212',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  DO: {
    name: 'Dominican Republic',
    iso: 'DO',
    id: '214',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: 'northern',
    },
  },
  DZ: {
    name: 'Algeria',
    iso: 'DZ',
    id: '012',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  EC: {
    name: 'Ecuador',
    iso: 'EC',
    id: '218',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: ['northern', 'southern'],
    },
  },
  EE: {
    name: 'Estonia',
    iso: 'EE',
    id: '233',
    attributes: {
      drivingSide: 'right',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  EG: {
    name: 'Egypt',
    iso: 'EG',
    id: '818',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  EH: {
    name: 'Western Sahara',
    iso: 'EH',
    id: '732',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  ER: {
    name: 'Eritrea',
    iso: 'ER',
    id: '232',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  ES: {
    name: 'Spain',
    iso: 'ES',
    id: '724',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  ET: {
    name: 'Ethiopia',
    iso: 'ET',
    id: '231',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  FI: {
    name: 'Finland',
    iso: 'FI',
    id: '246',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: ['white-white', 'yellow-white'],
      hemisphere: 'northern',
    },
  },
  FJ: {
    name: 'Fiji',
    iso: 'FJ',
    id: '242',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  FK: {
    name: 'Falkland Islands',
    iso: 'FK',
    id: '238',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  FM: {
    name: 'Micronesia',
    iso: 'FM',
    id: '583',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  FO: {
    name: 'Faroe Islands',
    iso: 'FO',
    id: '234',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  FR: {
    name: 'France',
    iso: 'FR',
    id: '250',
    attributes: {
      drivingSide: 'right',
      cameraGen: [1, 2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  GA: {
    name: 'Gabon',
    iso: 'GA',
    id: '266',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: ['northern', 'southern'],
    },
  },
  GB: {
    name: 'United Kingdom',
    iso: 'GB',
    id: '826',
    attributes: {
      drivingSide: 'left',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: ['white-white', 'white-yellow'],
      hemisphere: 'northern',
    },
  },
  GD: {
    name: 'Grenada',
    iso: 'GD',
    id: '308',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  GE: {
    name: 'Georgia',
    iso: 'GE',
    id: '268',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  GF: {
    name: 'French Guiana',
    iso: 'GF',
    id: '254',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  GG: {
    name: 'Guernsey',
    iso: 'GG',
    id: '831',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  GH: {
    name: 'Ghana',
    iso: 'GH',
    id: '288',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  GI: {
    name: 'Gibraltar',
    iso: 'GI',
    id: '292',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: ['white-white', 'white-yellow'],
      hemisphere: 'northern',
    },
  },
  GL: {
    name: 'Greenland',
    iso: 'GL',
    id: '304',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  GM: {
    name: 'The Gambia',
    iso: 'GM',
    id: '270',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  GN: {
    name: 'Guinea',
    iso: 'GN',
    id: '324',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  GP: {
    name: 'Guadeloupe',
    iso: 'GP',
    id: '312',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  GQ: {
    name: 'Equatorial Guinea',
    iso: 'GQ',
    id: '226',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: ['northern', 'southern'],
    },
  },
  GR: {
    name: 'Greece',
    iso: 'GR',
    id: '300',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  GS: {
    name: 'South Georgia and the South Sandwich Islands',
    iso: 'GS',
    id: '239',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  GT: {
    name: 'Guatemala',
    iso: 'GT',
    id: '320',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: 'northern',
    },
  },
  GU: {
    name: 'Guam',
    iso: 'GU',
    id: '316',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'no',
      roadLines: 'yellow-white',
      hemisphere: 'northern',
    },
  },
  GW: {
    name: 'Guinea-Bissau',
    iso: 'GW',
    id: '624',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  GY: {
    name: 'Guyana',
    iso: 'GY',
    id: '328',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  HK: {
    name: 'Hong Kong',
    iso: 'HK',
    id: '344',
    attributes: {
      drivingSide: 'left',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  HM: {
    name: 'Heard Island and McDonald Islands',
    iso: 'HM',
    id: '334',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  HN: {
    name: 'Honduras',
    iso: 'HN',
    id: '340',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  HR: {
    name: 'Croatia',
    iso: 'HR',
    id: '191',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  HT: {
    name: 'Haiti',
    iso: 'HT',
    id: '332',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  HU: {
    name: 'Hungary',
    iso: 'HU',
    id: '348',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  ID: {
    name: 'Indonesia',
    iso: 'ID',
    id: '360',
    attributes: {
      drivingSide: 'left',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: ['white-white', 'yellow-white'],
      hemisphere: ['northern', 'southern'],
    },
  },
  IE: {
    name: 'Ireland',
    iso: 'IE',
    id: '372',
    attributes: {
      drivingSide: 'left',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-yellow',
      hemisphere: 'northern',
    },
  },
  IL: {
    name: 'Israel',
    iso: 'IL',
    id: '376',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3],
      officialCoverage: 'yes',
      roadLines: 'white-yellow',
      hemisphere: 'northern',
    },
  },
  IM: {
    name: 'Isle of Man',
    iso: 'IM',
    id: '833',
    attributes: {
      drivingSide: 'right',
      cameraGen: 2,
      officialCoverage: 'yes',
      roadLines: ['white-white', 'white-yellow'],
      hemisphere: 'northern',
    },
  },
  IN: {
    name: 'India',
    iso: 'IN',
    id: '356',
    attributes: {
      drivingSide: 'left',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  IO: {
    name: 'British Indian Ocean Territory',
    iso: 'IO',
    id: '086',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  IQ: {
    name: 'Iraq',
    iso: 'IQ',
    id: '368',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  IR: {
    name: 'Iran',
    iso: 'IR',
    id: '364',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  IS: {
    name: 'Iceland',
    iso: 'IS',
    id: '352',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  IT: {
    name: 'Italy',
    iso: 'IT',
    id: '380',
    attributes: {
      drivingSide: 'right',
      cameraGen: [1, 2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  JE: {
    name: 'Jersey',
    iso: 'JE',
    id: '832',
    attributes: {
      drivingSide: 'right',
      cameraGen: 2,
      officialCoverage: 'yes',
      roadLines: 'white-yellow',
      hemisphere: 'northern',
    },
  },
  JM: {
    name: 'Jamaica',
    iso: 'JM',
    id: '388',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  JO: {
    name: 'Jordan',
    iso: 'JO',
    id: '400',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-yellow',
      hemisphere: 'northern',
    },
  },
  JP: {
    name: 'Japan',
    iso: 'JP',
    id: '392',
    attributes: {
      drivingSide: 'left',
      cameraGen: [1, 2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  KE: {
    name: 'Kenya',
    iso: 'KE',
    id: '404',
    attributes: {
      drivingSide: 'left',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: ['northern', 'southern'],
    },
  },
  KG: {
    name: 'Kyrgyzstan',
    iso: 'KG',
    id: '417',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  KH: {
    name: 'Cambodia',
    iso: 'KH',
    id: '116',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: 'northern',
    },
  },
  KI: {
    name: 'Kiribati',
    iso: 'KI',
    id: '296',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  KM: {
    name: 'Comoros',
    iso: 'KM',
    id: '174',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  KN: {
    name: 'Saint Kitts and Nevis',
    iso: 'KN',
    id: '659',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  KP: {
    name: 'North Korea',
    iso: 'KP',
    id: '408',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  KR: {
    name: 'South Korea',
    iso: 'KR',
    id: '410',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3],
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: 'northern',
    },
  },
  KW: {
    name: 'Kuwait',
    iso: 'KW',
    id: '414',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  KY: {
    name: 'Cayman Islands',
    iso: 'KY',
    id: '136',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  KZ: {
    name: 'Kazakhstan',
    iso: 'KZ',
    id: '398',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  LA: {
    name: 'Laos',
    iso: 'LA',
    id: '418',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  LB: {
    name: 'Lebanon',
    iso: 'LB',
    id: '422',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  LC: {
    name: 'Saint Lucia',
    iso: 'LC',
    id: '662',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  LI: {
    name: 'Liechtenstein',
    iso: 'LI',
    id: '438',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  LK: {
    name: 'Sri Lanka',
    iso: 'LK',
    id: '144',
    attributes: {
      drivingSide: 'left',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  LR: {
    name: 'Liberia',
    iso: 'LR',
    id: '430',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  LS: {
    name: 'Lesotho',
    iso: 'LS',
    id: '426',
    attributes: {
      drivingSide: 'left',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-yellow',
      hemisphere: 'southern',
    },
  },
  LT: {
    name: 'Lithuania',
    iso: 'LT',
    id: '440',
    attributes: {
      drivingSide: 'right',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  LU: {
    name: 'Luxembourg',
    iso: 'LU',
    id: '',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  LV: {
    name: 'Latvia',
    iso: 'LV',
    id: '442',
    attributes: {
      drivingSide: 'right',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  LY: {
    name: 'Libya',
    iso: 'LY',
    id: '434',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  MA: {
    name: 'Morocco',
    iso: 'MA',
    id: '504',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  MC: {
    name: 'Monaco',
    iso: 'MC',
    id: '492',
    attributes: {
      drivingSide: 'right',
      cameraGen: [1, 2, 3],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  MD: {
    name: 'Moldova',
    iso: 'MD',
    id: '498',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  ME: {
    name: 'Montenegro',
    iso: 'ME',
    id: '499',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  MF: {
    name: 'Saint Martin',
    iso: 'MF',
    id: '663',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  MG: {
    name: 'Madagascar',
    iso: 'MG',
    id: '450',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  MH: {
    name: 'Marshall Islands',
    iso: 'MH',
    id: '584',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  MK: {
    name: 'North Macedonia',
    iso: 'MK',
    id: '807',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: ['white-white', 'yellow-yellow'],
      hemisphere: 'northern',
    },
  },
  ML: {
    name: 'Mali',
    iso: 'ML',
    id: '466',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  MM: {
    name: 'Myanmar',
    iso: 'MM',
    id: '104',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  MN: {
    name: 'Mongolia',
    iso: 'MN',
    id: '496',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  MO: {
    name: 'Macao',
    iso: 'MO',
    id: '446',
    attributes: {
      drivingSide: 'left',
      cameraGen: 2,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  MP: {
    name: 'Northern Mariana Islands',
    iso: 'MP',
    id: '580',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: 'northern',
    },
  },
  MQ: {
    name: 'Martinique',
    iso: 'MQ',
    id: '580',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  MR: {
    name: 'Mauritania',
    iso: 'MR',
    id: '478',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  MS: {
    name: 'Montserrat',
    iso: 'MS',
    id: '500',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  MT: {
    name: 'Malta',
    iso: 'MT',
    id: '470',
    attributes: {
      drivingSide: 'left',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  MU: {
    name: 'Mauritius',
    iso: 'MU',
    id: '480',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  MV: {
    name: 'Maldives',
    iso: 'MV',
    id: '462',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: ['northern', 'southern'],
    },
  },
  MW: {
    name: 'Malawi',
    iso: 'MW',
    id: '454',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  MX: {
    name: 'Mexico',
    iso: 'MX',
    id: '484',
    attributes: {
      drivingSide: 'right',
      cameraGen: [1, 2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: 'northern',
    },
  },
  MY: {
    name: 'Malaysia',
    iso: 'MY',
    id: '458',
    attributes: {
      drivingSide: 'left',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  MZ: {
    name: 'Mozambique',
    iso: 'MZ',
    id: '508',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  NA: {
    name: 'Namibia',
    iso: 'NA',
    id: '516',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  NC: {
    name: 'New Caledonia',
    iso: 'NC',
    id: '540',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  NE: {
    name: 'Niger',
    iso: 'NE',
    id: '562',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  NF: {
    name: 'Norfolk Island',
    iso: 'NF',
    id: '574',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  NG: {
    name: 'Nigeria',
    iso: 'NG',
    id: '566',
    attributes: {
      drivingSide: 'right',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-yellow',
      hemisphere: 'northern',
    },
  },
  NI: {
    name: 'Nicaragua',
    iso: 'NI',
    id: '558',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  NL: {
    name: 'Netherlands',
    iso: 'NL',
    id: '528',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  NO: {
    name: 'Norway',
    iso: 'NO',
    id: '578',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: 'northern',
    },
  },
  NP: {
    name: 'Nepal',
    iso: 'NP',
    id: '524',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  NR: {
    name: 'Nauru',
    iso: 'NR',
    id: '520',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  NU: {
    name: 'Niue',
    iso: 'NU',
    id: '570',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  NZ: {
    name: 'New Zealand',
    iso: 'NZ',
    id: '554',
    attributes: {
      drivingSide: 'left',
      cameraGen: [1, 2, 3, 4],
      officialCoverage: 'yes',
      roadLines: [
        'white-white',
        'yellow-white',
        'white-yellow',
        'yellow-yellow',
        'yellow_white-white',
      ],
      hemisphere: 'southern',
    },
  },
  OM: {
    name: 'Oman',
    iso: 'OM',
    id: '512',
    attributes: {
      drivingSide: 'right',
      officialCoverage: 'no',
      cameraGen: null,
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  PA: {
    name: 'Panama',
    iso: 'PA',
    id: '591',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  PE: {
    name: 'Peru',
    iso: 'PE',
    id: '604',
    attributes: {
      drivingSide: 'right',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: ['white-white', 'yellow-white'],
      hemisphere: 'southern',
    },
  },
  PF: {
    name: 'French Polynesia',
    iso: 'PF',
    id: '258',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  PG: {
    name: 'Papua New Guinea',
    iso: 'PG',
    id: '324',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  PH: {
    name: 'Philippines',
    iso: 'PH',
    id: '608',
    attributes: {
      drivingSide: 'right',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: ['white-white', 'yellow-white', 'yellow_white-white'],
      hemisphere: 'northern',
    },
  },
  PK: {
    name: 'Pakistan',
    iso: 'PK',
    id: '586',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  PL: {
    name: 'Poland',
    iso: 'PL',
    id: '616',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  PM: {
    name: 'Saint Pierre and Miquelon',
    iso: 'PM',
    id: '666',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  PN: {
    name: 'Pitcairn',
    iso: 'PN',
    id: '612',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  PR: {
    name: 'Puerto Rico',
    iso: 'PR',
    id: '630',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: 'northern',
    },
  },
  PS: {
    name: 'Palestine',
    iso: 'PS',
    id: '275',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  PT: {
    name: 'Portugal',
    iso: 'PT',
    id: '620',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  PW: {
    name: 'Palau',
    iso: 'PW',
    id: '585',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  PY: {
    name: 'Paraguay',
    iso: 'PY',
    id: '600',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  QA: {
    name: 'Qatar',
    iso: 'QA',
    id: '634',
    attributes: {
      drivingSide: 'right',
      cameraGen: 4,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  RE: {
    name: 'Reunion',
    iso: 'RE',
    id: '638',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  RO: {
    name: 'Romania',
    iso: 'RO',
    id: '642',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  RS: {
    name: 'Serbia',
    iso: 'RS',
    id: '688',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  RU: {
    name: 'Russia',
    iso: 'RU',
    id: '643',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  RW: {
    name: 'Rwanda',
    iso: 'RW',
    id: '646',
    attributes: {
      drivingSide: 'right',
      cameraGen: 4,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  SA: {
    name: 'Saudi Arabia',
    iso: 'SA',
    id: '682',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  SB: {
    name: 'Solomon Islands',
    iso: 'SB',
    id: '090',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  SC: {
    name: 'Seychelles',
    iso: 'SC',
    id: '690',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  SD: {
    name: 'Sudan',
    iso: 'SD',
    id: '729',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  SE: {
    name: 'Sweden',
    iso: 'SE',
    id: '752',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  SG: {
    name: 'Singapore',
    iso: 'SG',
    id: '702',
    attributes: {
      drivingSide: 'left',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: ['white-white', 'white-yellow'],
      hemisphere: 'northern',
    },
  },
  SH: {
    name: 'Saint Helena',
    iso: 'SH',
    id: '654',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  SI: {
    name: 'Slovenia',
    iso: 'SI',
    id: '705',
    attributes: {
      drivingSide: 'right',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  SJ: {
    name: 'Svalbard and Jan Mayen',
    iso: 'SJ',
    id: '744',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  SK: {
    name: 'Slovakia',
    iso: 'SK',
    id: '703',
    attributes: {
      drivingSide: 'right',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  SL: {
    name: 'Sierra Leone',
    iso: 'SL',
    id: '694',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  SM: {
    name: 'San Marino',
    iso: 'SM',
    id: '674',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  SN: {
    name: 'Senegal',
    iso: 'SN',
    id: '686',
    attributes: {
      drivingSide: 'right',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  SO: {
    name: 'Somalia',
    iso: 'SO',
    id: '706',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: ['northern', 'southern'],
    },
  },
  SR: {
    name: 'Suriname',
    iso: 'SR',
    id: '740',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  SS: {
    name: 'South Sudan',
    iso: 'SS',
    id: '728',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  ST: {
    name: 'Sao Tome and Principe',
    iso: 'ST',
    id: '678',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  SV: {
    name: 'El Salvador',
    iso: 'SV',
    id: '222',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  SX: {
    name: 'Sint Maarten',
    iso: 'SX',
    id: '534',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  SY: {
    name: 'Syria',
    iso: 'SY',
    id: '760',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  SZ: {
    name: 'Eswatini',
    iso: 'SZ',
    id: '748',
    attributes: {
      drivingSide: 'left',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-yellow',
      hemisphere: 'southern',
    },
  },
  TC: {
    name: 'Turks and Caicos Islands',
    iso: 'TC',
    id: '796',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  TD: {
    name: 'Chad',
    iso: 'TD',
    id: '148',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  TF: {
    name: 'French Southern Territories',
    iso: 'TF',
    id: '260',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  TG: {
    name: 'Togo',
    iso: 'TG',
    id: '768',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  TH: {
    name: 'Thailand',
    iso: 'TH',
    id: '764',
    attributes: {
      drivingSide: 'left',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: 'northern',
    },
  },
  TJ: {
    name: 'Tajikistan',
    iso: 'TJ',
    id: '762',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  TK: {
    name: 'Tokelau',
    iso: 'TK',
    id: '772',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  TL: {
    name: 'Timor-Leste',
    iso: 'TL',
    id: '626',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  TM: {
    name: 'Turkmenistan',
    iso: 'TM',
    id: '795',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  TN: {
    name: 'Tunisia',
    iso: 'TN',
    id: '788',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  TO: {
    name: 'Tonga',
    iso: 'TO',
    id: '776',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  TR: {
    name: 'Turkey',
    iso: 'TR',
    id: '792',
    attributes: {
      drivingSide: 'right',
      cameraGen: [3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  TT: {
    name: 'Trinidad and Tobago',
    iso: 'TT',
    id: '780',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  TV: {
    name: 'Tuvalu',
    iso: 'TV',
    id: '798',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  TW: {
    name: 'Taiwan',
    iso: 'TW',
    id: '158',
    attributes: {
      drivingSide: 'right',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: 'northern',
    },
  },
  TZ: {
    name: 'Tanzania',
    iso: 'TZ',
    id: '834',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  UA: {
    name: 'Ukraine',
    iso: 'UA',
    id: '804',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  UG: {
    name: 'Uganda',
    iso: 'UG',
    id: '800',
    attributes: {
      drivingSide: 'left',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: ['white-white', 'yellow-white'],
      hemisphere: ['northern', 'southern'],
    },
  },
  UM: {
    name: 'United States Minor Outlying Islands',
    iso: 'UM',
    id: '581',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  US: {
    name: 'United States',
    iso: 'US',
    id: '840',
    attributes: {
      drivingSide: 'right',
      cameraGen: [1, 2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'yellow-white',
      hemisphere: 'northern',
    },
  },
  UY: {
    name: 'Uruguay',
    iso: 'UY',
    id: '858',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  UZ: {
    name: 'Uzbekistan',
    iso: 'UZ',
    id: '860',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  VA: {
    name: 'Vatican',
    iso: 'VA',
    id: '336',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  VC: {
    name: 'Saint Vincent and the Grenadines',
    iso: 'VC',
    id: '670',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  VE: {
    name: 'Venezuela',
    iso: 'VE',
    id: '862',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  VG: {
    name: 'British Virgin Islands',
    iso: 'VG',
    id: '092',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  VI: {
    name: 'U.S. Virgin Islands',
    iso: 'VI',
    id: '850',
    attributes: {
      drivingSide: 'right',
      cameraGen: 3,
      officialCoverage: 'yes',
      roadLines: 'yellow_white-white',
      hemisphere: 'northern',
    },
  },
  VN: {
    name: 'Vietnam',
    iso: 'VN',
    id: '704',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: ['white-white', 'yellow-white'],
      hemisphere: 'northern',
    },
  },
  VU: {
    name: 'Vanuatu',
    iso: 'VU',
    id: '548',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'yes',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  WF: {
    name: 'Wallis and Futuna',
    iso: 'WF',
    id: '876',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  WS: {
    name: 'Samoa',
    iso: 'WS',
    id: '882',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },

  YE: {
    name: 'Yemen',
    iso: 'YE',
    id: '887',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'northern',
    },
  },
  YT: {
    name: 'Mayotte',
    iso: 'YT',
    id: '175',
    attributes: {
      drivingSide: 'right',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  ZA: {
    name: 'South Africa',
    iso: 'ZA',
    id: '710',
    attributes: {
      drivingSide: 'left',
      cameraGen: [2, 3, 4],
      officialCoverage: 'yes',
      roadLines: 'white-yellow',
      hemisphere: 'southern',
    },
  },
  ZM: {
    name: 'Zambia',
    iso: 'ZM',
    id: '894',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
  ZW: {
    name: 'Zimbabwe',
    iso: 'ZW',
    id: '716',
    attributes: {
      drivingSide: 'left',
      cameraGen: null,
      officialCoverage: 'no',
      roadLines: 'white-white',
      hemisphere: 'southern',
    },
  },
};
